<?php

// config ------------------------------ //

$output_file = "events_data.h";
$audacity_project = 'bt.aup';

// --------------------------------------//

$doc = new DOMDocument();
$doc->preserveWhiteSpace = false;
$doc->load($audacity_project);

$xp = new DOMXPath($doc);
$xp->registerNamespace('audacity', 'http://audacity.sourceforge.net/xml/');

// For each label track, extract its labels and time
$label_tracks = $xp->query('//audacity:labeltrack');
$tracks_array = array();

if(!is_null($label_tracks))
{
	foreach($label_tracks as $k => $track)
	{
		$times_array = array();
		
		$children = $track->childNodes;
		
		foreach($children as $label)
		{
			$value = $label->getAttribute('t');
			$value = round($value, 3) . 'f';
			$times_array[]= $value;
		}
		
		$tracks_array[]= $times_array;
	}
}

// Now generate the output file
$fh = fopen($output_file, "w");

$tpl = "// WARNING! AUTOGENERATED DATA\n";

foreach($tracks_array as $k => $track)
{
	$tpl .= "int num_events$k = " . count($track) . ";\n";
	$tpl .= "int pos_events$k = 0;\n";
	$tpl .= "float events$k". '['. count($track). '] = {' . join(', ', $track) . '}' . ";\n\n" ;
}

fputs($fh, $tpl);

fclose($fh);
?>
